### ISSUE TITLE
Resource does not exist: /target/classes/META-INF/takari/mojos.xml

### ISSUE THREAD

**Issue by guw** [takari/takari-lifecycle#72] opened 2018-06-22 08:25 UTC
I see the following exception/error reported for two Maven plugins inside Eclipse Photon:

```
org.apache.maven.plugin.PluginExecutionException: Execution default-plugin-descriptor of goal io.takari.maven.plugins:takari-lifecycle-plugin:1.13.5:plugin-descriptor failed: Resource does not exist .../target/classes/META-INF/takari/mojos.xml
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
...
Caused by: java.lang.IllegalArgumentException: Resource does not exist .../target/classes/META-INF/takari/mojos.xml
	at io.takari.incrementalbuild.spi.AbstractBuildContext.registerInput(AbstractBuildContext.java:330)
	at io.takari.incrementalbuild.spi.AbstractBuildContext.registerNormalizedInput(AbstractBuildContext.java:291)
	at io.takari.incrementalbuild.spi.AbstractBuildContext.registerInput(AbstractBuildContext.java:318)
	at io.takari.incrementalbuild.aggregator.internal.DefaultAggregatorBuildContext.registerInput(DefaultAggregatorBuildContext.java:56)
	at io.takari.incrementalbuild.aggregator.internal.DefaultInputSet.addInput(DefaultInputSet.java:27)
	at io.takari.maven.plugins.plugin.PluginDescriptorMojo.executeMojo(PluginDescriptorMojo.java:113)
	at io.takari.maven.plugins.TakariLifecycleMojo.execute(TakariLifecycleMojo.java:99)
```

Is this an issue with Takari or M2E?

**Comment by ifedorenko** [comment] 2018-06-22 10:41
My _guess_ the problem is somewhere between https://github.com/takari/io.takari.m2e.lifecycle, m2e and maybe jdt.

There was a recent [discussion on takari user](https://groups.google.com/forum/?hl=en#!topic/takari-team-user/RLglK8fY5HQ) about this, where somebody provided a small project that reproduces the problem reliably. For me, however, the problem is intermittent and goes away after I refresh in Eclipse, so I never felt motivated enough to investigate.

**Comment by guw** [comment] 2018-06-22 10:53
Yes, I was able to get it away by just refreshing. However, today I tried for quite a bit the Refresh - Update Project - Clean dance but couldn't get it fixed.

**Comment by ifedorenko** [comment] 2018-07-01 02:58
fixed by https://github.com/takari/io.takari.m2e.lifecycle/commit/5ebed77abbed9cbbf06528653e922122fa148fde

**Closed by ifedorenko** 2018-07-01 02:58 UTC
