### ISSUE TITLE
Getting test errors when building in a linux with maven 3.2.5 and java 1.8

### ISSUE THREAD

**Issue by cvgaviao** [takari/takari-lifecycle#11] opened 2015-02-23 15:03 UTC
I'm getting errors when running the build. I'm using maven 3.2.5 in linux with java 1.8.0_31:

    Tests in error:
      BasicTest.initializationError » IO Input is not in the .gz format
      CompileAnnotationProcessingTest.initializationError » IO Input is not in the ....
      CompileClasspathTest.initializationError » IO Input is not in the .gz format
      CompileMultimoduleTest.initializationError » IO Input is not in the .gz format
      FilteringResourcesTest.initializationError » IO Input is not in the .gz format
      MultimoduleSkipInstallDeployTest.initializationError » IO Input is not in the ...
      PomPackagingTest.initializationError » IO Input is not in the .gz format

Further investigation points that apache-maven artifact version 3.2.3, that is somehow required by takari tests, is being downloaded damaged or it is corrupted when using it.

more details can be found here [1].

[1] - http://osdir.com/ml/general/2015-02/msg25912.html

**Comment by ifedorenko** [comment] 2015-02-23 15:33
Takari lifecycle integration tests are run against maven 3.2.3, 3.2.5 and 3.2.6-SNAPSHOT, so the build is expected to download these versions of Maven. As I mentioned on the mailing list, I suspect something in your environment prevents successful download of the required maven distribution. 

Few questions to help us narrow down the problem, 
* what linux distribution and full java version do you use?
  * note that takari lifecycle does not support openjdk, you need to use oracle java
* does your environment use restrictive firewall and/or antivirus software that may interfere with remote http/https access?
* does your environment require use of a proxy server to access remote http/https resources?
* does your user settings.xml file have custom and/or password-protected  <repository> or <mirror> elements?
* can you check if corrupted .gz file contains anything useful? for example, it may be http response text that may help identify the root cause.

**Comment by cvgaviao** [comment] 2015-02-23 17:33
what I observed was that only 3.2.3 was downloaded after I have removed all versions from my local repository.
my linux is Ubuntu LTS 10.04
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

- I have a firewall set on my machine, but it is the first time that I saw such behavior. I have lot of maven projects that build against maven central and other repositories, including p2 ones.
- No, I haven't a proxy here.
- My settings.xml doesn't have any password-protected elements.
- No, I can't open the downloaded .gz file

**Comment by cvgaviao** [comment] 2015-02-23 17:45
Do you know any other project that would require the apache-maven artifact ?

**Comment by ifedorenko** [comment] 2015-02-23 18:09
* Can you 'cat' the corrupted gz file? 
* Are you able to downloaf https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.2.3/apache-maven-3.2.3-bin.tar.gz using curl or wget on command line?
* Does your settings.xml have <mirror> or <repository> elements? Plugin testing harness will access all repositories/mirrors configured in settings.xml and if any responds with http 2xx status code it will use the response body.
* You may want to import takari-lifecycle sources in m2e and put breakpoint in MavenVersionResolver.downloadMaven to see what actually happens there.

**Comment by cvgaviao** [comment] 2015-02-23 18:51
- Humm :) I just tried to open the file using the nautilus extractor... 
That is the content:
```html
    <html>
    <head><title>301 Moved Permanently</title></head>
    <body bgcolor="white">
    <center><h1>301 Moved Permanently</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>
```
- my  settings.xml hasn't any mirror, but has some profiles containing repositories, most of them are p2.

- will do that...

**Comment by ifedorenko** [comment] 2015-02-23 18:58
try building without settings.xml or with `mvn -s` pointing at empty settings.xml. this will tell you if the problem is caused by your settings.xml repositories or something else.

**Comment by cvgaviao** [comment] 2015-02-23 20:04
No good luck debugging takari so far :(.
I have been using the plugin you created to debug a couple of months. I can debug my own plugins, adding break points everywhere without any issues. and all that I needed for them was to set "Resolve Workspace artifacts" on. :/
Yesterday I installed Takari Team. and my stuffs still working well.
But I'm a lot of time fighting and I can't make the breakpoints on the takari-plugin-testing class to work :(
I tried to put one breakpoint in the io.tesla.maven.plugins.test.BasicTest class too. but it is not working either. 
I'm without ideas...  maybe I'm missing something needed to debug these projects?
It starts to build and seems that will work, but it doesn't stop: 

    Dynamic source lookup support loaded.
    Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T14:29:23-03:00)
    Maven home: /home/cvgaviao/Development/Development_Github/takari-lifecycle/EMBEDDED
    Java version: 1.8.0_31, vendor: Oracle Corporation
    Java home: /usr/lib/jvm/java-8-oracle/jre
    Default locale: en_US, platform encoding: UTF-8
    OS name: "linux", version: "3.13.0-45-generic", arch: "amd64", family: "unix"
    [INFO] Error stacktraces are turned on.

**Comment by ifedorenko** [comment] 2015-02-23 20:58
Can you right-click on io.tesla.maven.plugins.test.BasicTest, then Run As Maven JUnit Test? (note maven-specific junit test launcher).

**Comment by cvgaviao** [comment] 2015-02-23 23:15
Yep, you were right. Using this 'run as maven junit test' (that btw is really cool) I was able to debug. Running with a clean setting.xml the plugin was able to download the artifact from maven central properly. So, the problem certainly is in one of the repositories that I have in my settings.xml.

Well, don't you think that would be safer to put a kind of *weight* in order to prefer the maven central (if it is on the resolved repository list) when looking for those core maven stuffs? It would at least avoid breaking buildings caused by some bad repository provided by third OSS projects that we require in our buildings.

Anyway, I still have issues in all Integration Tests, look one:
```html
java.lang.AssertionError: [[ERROR] Failed to execute goal io.takari.maven.plugins:takari-lifecycle-plugin:1.11.0-SNAPSHOT:process-resources (default-process-resources) on project basic: Execution default-process-resources of goal io.takari.maven.plugins:takari-lifecycle-plugin:1.11.0-SNAPSHOT:process-resources failed: Unable to load the mojo 'process-resources' (or one of its required components) from the plugin 'io.takari.maven.plugins:takari-lifecycle-plugin:1.11.0-SNAPSHOT': com.google.inject.ProvisionException: Guice provision errors:, [ERROR] , [ERROR] 1) No implementation for io.takari.resources.filtering.ResourcesProcessor was bound., [ERROR] while locating io.takari.maven.plugins.resources.ProcessResources, [ERROR] at ClassRealm[plugin>io.takari.maven.plugins:takari-lifecycle-plugin:1.11.0-SNAPSHOT, parent: sun.misc.Launcher$AppClassLoader@58644d46], [ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=io.takari.maven.plugins:takari-lifecycle-plugin:1.11.0-SNAPSHOT:process-resources), [ERROR] , [ERROR] 1 error, [ERROR] role: org.apache.maven.plugin.Mojo, [ERROR] roleHint: io.takari.maven.plugins:takari-lifecycle-plugin:1.11.0-SNAPSHOT:process-resources, [ERROR] -> [Help 1], [ERROR] , [ERROR] , [ERROR] For more information about the errors and possible solutions, please read the following articles:, [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException]
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at io.takari.maven.testing.executor.MavenExecutionResult.assertErrorFreeLog(MavenExecutionResult.java:44)
	at io.tesla.maven.plugins.test.BasicTest.testBasic(BasicTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.ifedorenko.m2e.mavendev.junit.runtime.internal.RemoteTestRunner.run(RemoteTestRunner.java:43)
	at com.ifedorenko.m2e.mavendev.junit.runtime.internal.RemoteTestRunner.main(RemoteTestRunner.java:30)

````
ideas ?

**Comment by ifedorenko** [comment] 2015-02-23 23:21
What remote repository is causing the problem? Can you provide URL I can test locally?

List of repositories is already ordered. If you want Maven Central to come first, just add it first in settings.xml.

You are getting test failures likely because Maven plugin.xml is missing. Known limitation of maven-plugin-plugin, which we plan to replace with proper incremental implementation some time in the future. Do Project->Clean of the takari-lifecycle projects in Eclipse to get Maven plugin.xml generated inside Eclipse for now.

**Comment by cvgaviao** [comment] 2015-02-23 23:58
I will investigate which OSS repository in my profiles is the culprit and send to you tomorrow.

Well, in my case I don't have the maven central in the settings.xml. Never cared about to add it explicitly because code I noted once that it always come when getting the computed repositories. But seems that I will need to do this time.

**Comment by cvgaviao** [comment] 2015-02-24 00:49
Here are the culprits repositories: 
- http://oss.sonatype.org/content/repositories/vaadin-releases/

This is strange because it is a snapshot repository, it is declared as snapshot in settings.xml :
````html
<repository>
					<id>takari-s</id>
					<url>http://repository.takari.io:8081/nexus/content/repositories/snapshots/
					</url>
					<releases>
						<enabled>false</enabled>
					</releases>
					<snapshots>
						<updatePolicy>always</updatePolicy>
						<enabled>true</enabled>
					</snapshots>
				</repository>
````
But a damaged release artifact (160bytes) are being downloaded from here:
    http://repository.takari.io:8081/nexus/content/repositories/snapshots/org/apache/maven/apache-maven/3.2.3/apache-maven-3.2.3-bin.tar.gz

About the tests, still can't run them.
Even doing Project->Clean I couldn't not see the plugin.xml being generated.

**Comment by cvgaviao** [comment] 2015-02-24 01:17
Great. Finally I was able to debug the tests using 'run as maven junit test'. I had to build takari-lifecycle projects using maven. then I  call "maven->update project" on them.

**Comment by ifedorenko** [comment] 2015-02-24 12:44
Ok, thanks, I think I know how to fix this. 

Btw, please update takari.io repository to https://repository.takari.io url, like https://repository.takari.io/content/repositories/snapshots.

**Comment by ifedorenko** [comment] 2015-02-24 15:55
Should be fixed now. The immediate problem should be addressed by https://github.com/takari/takari-plugin-testing-project/commit/cffb61394560b866f7bd845f1a67441f8b32e811 and https://github.com/takari/takari-plugin-testing-project/commit/94bcf1c109949aeb378cc5e7f31eef6748d1220b . Also changed test runtime download logic to work better in multi-threaded/multi-process environments.

**Closed by ifedorenko** 2015-02-24 15:55 UTC

**Comment by cvgaviao** [comment] 2015-02-24 16:22
Thanks Igor !
